apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: russia2018
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: russia2018
        uses: redis
    spec:
      containers:
      - name: russia2018
        image: gcr.io/node-example-gke/russia2018:c852b86b45547cec9b36e979a7984924964bd63e
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: WEBSOCKET_PATH
          value: /websocket
        - name: TWITTER_KEY
          valueFrom:
            secretKeyRef:
              name: russia2018-secret
              key: twitter_key
        - name: TWITTER_SECRET
          valueFrom:
            secretKeyRef:
              name: russia2018-secret
              key: twitter_secret
        - name: TWITTER_TOKEN
          valueFrom:
            secretKeyRef:
              name: russia2018-secret
              key: twitter_token
        - name: TWITTER_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: russia2018-secret
              key: twitter_token_secret
        - name: FOOTBALLDATA_TOKEN
          valueFrom:
            secretKeyRef:
              name: russia2018-secret
              key: footballdata_token
        ports:
        - containerPort: 3002
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /status?livenessProbe=1
            port: 4440
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /status?readinessProbe=1
            port: 4440
          initialDelaySeconds: 15
          timeoutSeconds: 1
